version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - ENV=local
    depends_on:
      - php

  php:
    image: php:fpm
    volumes:
      - .:/var/www/html
    environment:
      - ENV=local